# Generated by Django 4.1.2 on 2023-01-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('comments', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
